from typing import Protocol


class CoordinationProtocol(Protocol):
    async def ping(self) -> bool: ...

    async def incr_with_expire(self, key: str, expire_sec: int) -> int: ...

    async def set_nx(self, key: str, value: str, ttl_sec: int) -> bool: ...

    async def delete(self, key: str) -> None: ...
