[project]
name = "gateway"
dynamic = ["version"]
description = "gateway service"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.0",
    "pydantic>=2.12.5",
    "pyyaml>=6.0",
    "structlog>=25.5.0",
    "dishka>=1.7.2",
    "pydantic-settings>=2.12.0",
    "python-dotenv>=1.2.1",
    "grpclib[protobuf]>=0.4.9",
    "protobuf>=5.28.0",
    "typing-extensions>=4.15.0",
    "aiogram>=3.27.0",
    "redis>=7.4.0",
    "valkey-glide>=2.2.3; platform_system != 'Windows'",
    "prometheus-client>=0.24.1",
]

[dependency-groups]
dev = [
    "basedpyright>=1.36.1",
    "hatch>=1.16.2",
    "mypy>=1.19.1",
    "ruff>=0.14.9",
    "rust-just>=1.45.0",
    "types-protobuf>=5.28.0",
]
testing = [
    "pytest>=9.0.2",
    "pytest-asyncio>=0.23.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
only-packages = true
packages = ["gateway"]

[tool.hatch.version]
path = "gateway/__version__.py"

[tool.uv]
package = true

[tool.basedpyright]
venvPath = "."
venv = ".venv"
pythonVersion = "3.13"
pythonPlatform = "Linux"
reportMissingImports = "error"
reportMissingTypeStubs = false
reportUnknownMemberType = false
reportUnusedParameter = "warning"
exclude = ["**/.venv", "**/__pycache__", "gateway_api", "gateway/tests", "scripts"]
typeCheckingMode = "recommended"

[tool.mypy]
exclude = [".*_test.py", "gateway_api", "scripts"]
plugins = "pydantic.mypy"

[tool.ruff]
exclude = [".venv", "gateway_api", "scripts"]
line-length = 120
indent-width = 4
target-version = "py313"
fix = true

[tool.ruff.format]
preview = true

[tool.ruff.lint]
select = ["ALL"]
fixable = ["ALL"]
ignore = ["ANN", "D", "EM101", "RUF001", "BLE001", "SIM103", "ASYNC109", "TRY003", "PLW0602", "TC001", "ISC003", "COM812", "RUF003", "RUF002", "TRY301"]
unfixable = []

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401", "TID252", "PLC0414"]
"**/{tests,docs,tools}/*" = ["E402"]
"gateway/tests/**/*" = ["S101"]
"*_test.py" = ["ANN", "S", "S101", "TRY", "PGH003", "FBT", "PT012", "N801", "ARG002", "SLF001", "PLR", "SIM"]

[tool.ruff.lint.flake8-bandit]
check-typed-exception = true

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.pycodestyle]
max-line-length = 128

[tool.pytest.ini_options]
pythonpath = "."
testpaths = ["gateway", "gateway/tests"]
addopts = []
filterwarnings = ["ignore::DeprecationWarning"]
python_files = ["*_test.py", "test_*.py"]
python_classes = "Test_*"
asyncio_mode = "auto"
