# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: api/match_api/v1/match.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.client
import grpclib.const

if typing.TYPE_CHECKING:
    import grpclib.server

import external_clients.match_api.v1.match_pb2 as match_pb2


class MatchServiceBase(abc.ABC):
    @abc.abstractmethod
    async def Health(
        self,
        stream: "grpclib.server.Stream[match_pb2.HealthRequest, match_pb2.HealthResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def HandleLike(
        self,
        stream: "grpclib.server.Stream[match_pb2.HandleLikeRequest, match_pb2.HandleLikeResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def HandleSkip(
        self,
        stream: "grpclib.server.Stream[match_pb2.HandleSkipRequest, match_pb2.HandleSkipResponse]",
    ) -> None:
        pass

    def __mapping__(self) -> dict[str, grpclib.const.Handler]:
        return {
            "/match_api.v1.MatchService/Health": grpclib.const.Handler(
                self.Health,
                grpclib.const.Cardinality.UNARY_UNARY,
                match_pb2.HealthRequest,
                match_pb2.HealthResponse,
            ),
            "/match_api.v1.MatchService/HandleLike": grpclib.const.Handler(
                self.HandleLike,
                grpclib.const.Cardinality.UNARY_UNARY,
                match_pb2.HandleLikeRequest,
                match_pb2.HandleLikeResponse,
            ),
            "/match_api.v1.MatchService/HandleSkip": grpclib.const.Handler(
                self.HandleSkip,
                grpclib.const.Cardinality.UNARY_UNARY,
                match_pb2.HandleSkipRequest,
                match_pb2.HandleSkipResponse,
            ),
        }


class MatchServiceStub:
    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Health = grpclib.client.UnaryUnaryMethod(
            channel,
            "/match_api.v1.MatchService/Health",
            match_pb2.HealthRequest,
            match_pb2.HealthResponse,
        )
        self.HandleLike = grpclib.client.UnaryUnaryMethod(
            channel,
            "/match_api.v1.MatchService/HandleLike",
            match_pb2.HandleLikeRequest,
            match_pb2.HandleLikeResponse,
        )
        self.HandleSkip = grpclib.client.UnaryUnaryMethod(
            channel,
            "/match_api.v1.MatchService/HandleSkip",
            match_pb2.HandleSkipRequest,
            match_pb2.HandleSkipResponse,
        )
