# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: gateway_api/v1/gateway.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import gateway_api.v1.gateway_pb2


class GatewayServiceBase(abc.ABC):

    @abc.abstractmethod
    async def Ping(self, stream: 'grpclib.server.Stream[gateway_api.v1.gateway_pb2.PingRequest, gateway_api.v1.gateway_pb2.PingResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/gateway_api.v1.GatewayService/Ping': grpclib.const.Handler(
                self.Ping,
                grpclib.const.Cardinality.UNARY_UNARY,
                gateway_api.v1.gateway_pb2.PingRequest,
                gateway_api.v1.gateway_pb2.PingResponse,
            ),
        }


class GatewayServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Ping = grpclib.client.UnaryUnaryMethod(
            channel,
            '/gateway_api.v1.GatewayService/Ping',
            gateway_api.v1.gateway_pb2.PingRequest,
            gateway_api.v1.gateway_pb2.PingResponse,
        )
